"""Extended Multi-LM PPL with multiple INSTRUCT-tuned LMs.

Hipoteza: dataset watermarked text generated by INSTRUCT model
(eksplanacyjny Q&A styl). OLMo-Instruct dało 0.158 leaderboard (jump
z 0.103). Amplifikujemy sygnał używając wielu instruct LMs z różnych
rodzin:

  - Phi-2 (Microsoft, 2.7B, public)               # NEW, no auth
  - OLMo-2-1B-Instruct (Allen AI, 1B, public)     # already in features_multi_lm
  - Llama-2-7B-chat-hf (Meta, 7B, gated)          # NEW, requires HF_TOKEN
  - Mistral-7B-Instruct-v0.1 (gated, 7B)          # NEW, requires HF_TOKEN
  - Qwen2-0.5B-Instruct (Alibaba, public)         # NEW, no auth

Models loaded all at once (~25GB GPU). Inference: 1 forward pass per LM
per text. ~5-10 min total z cache.
"""
from __future__ import annotations

import os

import numpy as np
import torch

# Configuration: (name, requires_auth, weight_disp_name)
LMS = [
    ("microsoft/Phi-2", False, "phi2"),
    ("Qwen/Qwen2-0.5B-Instruct", False, "qwen2"),
    ("meta-llama/Llama-2-7b-chat-hf", True, "lchat"),
    ("mistralai/Mistral-7B-Instruct-v0.1", True, "mchat"),
]

_models: dict[str, tuple[object, object]] = {}  # name -> (tokenizer, model)
_DEVICE: str | None = None


def _device() -> str:
    global _DEVICE
    if _DEVICE is None:
        if torch.cuda.is_available():
            _DEVICE = "cuda"
        elif torch.backends.mps.is_available():
            _DEVICE = "mps"
        else:
            _DEVICE = "cpu"
    return _DEVICE


def _load() -> None:
    if _models:
        return
    from transformers import AutoModelForCausalLM, AutoTokenizer

    dev = _device()
    use_fp16 = dev == "cuda"
    dtype = torch.float16 if use_fp16 else torch.float32
    token = os.environ.get("HF_TOKEN")

    for name, needs_auth, _ in LMS:
        try:
            kwargs = {"token": token} if needs_auth and token else {}
            print(f"  [mlm_v2] Loading {name}...")
            tok = AutoTokenizer.from_pretrained(name, **kwargs)
            mod = AutoModelForCausalLM.from_pretrained(name, torch_dtype=dtype, **kwargs).to(dev).eval()
            _models[name] = (tok, mod)
        except Exception as e:
            print(f"  [mlm_v2] FAILED {name}: {e}")


@torch.no_grad()
def _ppl_features(text: str, tok, model, max_len: int = 1024) -> dict[str, float]:
    try:
        token_ids = tok.encode(text, truncation=True, max_length=max_len)
    except Exception:
        return {"lp_mean": 0.0, "lp_std": 0.0, "lp_p10": 0.0, "lp_p90": 0.0, "ppl": 1.0}

    if len(token_ids) < 2:
        return {"lp_mean": 0.0, "lp_std": 0.0, "lp_p10": 0.0, "lp_p90": 0.0, "ppl": 1.0}

    ids = torch.tensor([token_ids], dtype=torch.long).to(_device())
    logits = model(ids).logits[0, :-1].float()
    targets = ids[0, 1:]
    log_probs = torch.log_softmax(logits, dim=-1)
    lp = log_probs.gather(1, targets.unsqueeze(1)).squeeze(1).cpu().numpy()
    return {
        "lp_mean": float(lp.mean()),
        "lp_std": float(lp.std()),
        "lp_p10": float(np.percentile(lp, 10)),
        "lp_p90": float(np.percentile(lp, 90)),
        "ppl": float(np.exp(-lp.mean())),
    }


def extract(text: str) -> dict[str, float]:
    _load()
    feats: dict[str, float] = {}
    for name, _, prefix in LMS:
        if name not in _models:
            for k in ("lp_mean", "lp_std", "lp_p10", "lp_p90", "ppl"):
                feats[f"{prefix}_{k}"] = 0.0
            continue
        tok, mod = _models[name]
        sub = _ppl_features(text, tok, mod)
        for k, v in sub.items():
            feats[f"{prefix}_{k}"] = v
    return feats
