"""Multi-LM PPL fingerprinting.

Compute mean log-prob under multiple LMs. Add aggregator features:
- "natural" LM (which gives highest log-prob for this text)
- ratios between LMs (diff between best and worst)
- variance across LMs

If watermarked text was generated by LM X, PPL under X będzie szczególnie
niski. Across multiple LMs we identify the "fingerprint" — which LM jest
najbardziej zgodny z tekstem.

Models: opt-1.3b (additional, not yet covered) + reuses cached features
   gpt2 (in features_bino), pythia-1.4b (bino_strong), pythia-2.8b (bino_xl/_strong),
   pythia-6.9b (bino_xl).
"""
from __future__ import annotations

import numpy as np
import torch

_tok = None
_model = None
_DEVICE: str | None = None
MODEL_NAME = "facebook/opt-1.3b"


def _device() -> str:
    global _DEVICE
    if _DEVICE is None:
        if torch.cuda.is_available():
            _DEVICE = "cuda"
        elif torch.backends.mps.is_available():
            _DEVICE = "mps"
        else:
            _DEVICE = "cpu"
    return _DEVICE


def _load() -> None:
    global _tok, _model
    if _tok is not None:
        return
    from transformers import AutoModelForCausalLM, AutoTokenizer

    dev = _device()
    use_fp16 = dev == "cuda"
    dtype = torch.float16 if use_fp16 else torch.float32
    print(f"  [mlm] Loading {MODEL_NAME} on {dev} ({dtype})...")
    _tok = AutoTokenizer.from_pretrained(MODEL_NAME)
    _model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, torch_dtype=dtype).to(dev).eval()


@torch.no_grad()
def extract(text: str, max_len: int = 1024) -> dict[str, float]:
    _load()
    assert _tok is not None and _model is not None

    ids = _tok(text, return_tensors="pt", truncation=True, max_length=max_len).input_ids.to(_device())
    if ids.shape[1] < 2:
        return {"opt_lp_mean": 0.0, "opt_lp_std": 0.0, "opt_lp_p10": 0.0, "opt_lp_p90": 0.0,
                "opt_ppl": 1.0}

    logits = _model(ids).logits[0, :-1].float()
    targets = ids[0, 1:]
    log_probs = torch.log_softmax(logits, dim=-1)
    lp = log_probs.gather(1, targets.unsqueeze(1)).squeeze(1).cpu().numpy()

    return {
        "opt_lp_mean": float(lp.mean()),
        "opt_lp_std": float(lp.std()),
        "opt_lp_p10": float(np.percentile(lp, 10)),
        "opt_lp_p90": float(np.percentile(lp, 90)),
        "opt_ppl": float(np.exp(-lp.mean())),
    }
