"""Multi-LM PPL fingerprinting.

Compute mean log-prob under additional LM (OLMo-1B-Instruct, Allen AI family).
Pythia models (cached, used in bino_strong/xl) are EleutherAI training data.
OLMo is from Allen AI with different training corpus → orthogonal signal.

If watermarked text was generated by LM X, PPL under X będzie szczególnie
niski. OLMo PPL relative to Pythia PPL gives "LM family fingerprint".

NOTE: opt-1.3b initially tried but its tokenizer crashes with NoneType.endswith
on cluster (Python tokenizers library version mismatch). Switched to OLMo.
"""
from __future__ import annotations

import numpy as np
import torch

_tok = None
_model = None
_DEVICE: str | None = None
MODEL_NAME = "allenai/OLMo-2-0425-1B-Instruct"


def _device() -> str:
    global _DEVICE
    if _DEVICE is None:
        if torch.cuda.is_available():
            _DEVICE = "cuda"
        elif torch.backends.mps.is_available():
            _DEVICE = "mps"
        else:
            _DEVICE = "cpu"
    return _DEVICE


def _load() -> None:
    global _tok, _model
    if _tok is not None:
        return
    from transformers import AutoModelForCausalLM, AutoTokenizer

    dev = _device()
    use_fp16 = dev == "cuda"
    dtype = torch.float16 if use_fp16 else torch.float32
    print(f"  [mlm] Loading {MODEL_NAME} on {dev} ({dtype})...")
    _tok = AutoTokenizer.from_pretrained(MODEL_NAME)
    _model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, torch_dtype=dtype).to(dev).eval()


_ZERO_FEATS = {"olmo_lp_mean": 0.0, "olmo_lp_std": 0.0, "olmo_lp_p10": 0.0, "olmo_lp_p90": 0.0,
               "olmo_ppl": 1.0}


@torch.no_grad()
def extract(text: str, max_len: int = 1024) -> dict[str, float]:
    _load()
    assert _tok is not None and _model is not None

    # Use encode() directly — OPT's __call__ has issues with padding logic on cluster.
    try:
        token_ids = _tok.encode(text, truncation=True, max_length=max_len)
    except Exception:
        return dict(_ZERO_FEATS)

    if len(token_ids) < 2:
        return dict(_ZERO_FEATS)

    ids = torch.tensor([token_ids], dtype=torch.long).to(_device())

    logits = _model(ids).logits[0, :-1].float()
    targets = ids[0, 1:]
    log_probs = torch.log_softmax(logits, dim=-1)
    lp = log_probs.gather(1, targets.unsqueeze(1)).squeeze(1).cpu().numpy()

    return {
        "olmo_lp_mean": float(lp.mean()),
        "olmo_lp_std": float(lp.std()),
        "olmo_lp_p10": float(np.percentile(lp, 10)),
        "olmo_lp_p90": float(np.percentile(lp, 90)),
        "olmo_ppl": float(np.exp(-lp.mean())),
    }
